#+TITLE: Omni-scratch.el

/Scratch buffers one command away/

:warning: /Still Instable, existing Api might change/

[[https://travis-ci.org/AdrieanKhisbe/omni-scratch.el][file:https://travis-ci.org/AdrieanKhisbe/omni-scratch.el.svg]]
[[https://coveralls.io/r/AdrieanKhisbe/omni-scratch.el][file:https://coveralls.io/repos/AdrieanKhisbe/omni-scratch.el/badge.svg]]
[[http://melpa.org/#/omni-scratch][file:http://melpa.org/packages/omni-scratch-badge.svg]]
[[http://stable.melpa.org/#/omni-scratch][file:http://stable.melpa.org/packages/omni-scratch-badge.svg]]
[[https://github.com/AdrieanKhisbe/omni-scratch.el/tags][file:https://img.shields.io/github/tag/AdrieanKhisbe/omni-scratch.el.svg]]
[[http://www.gnu.org/licenses/gpl-3.0.html][http://img.shields.io/:license-gpl3-blue.svg]]

* Description

The goal of this basic mode is to easily create scratch buffer to edit in the curreny major mode you are using.
Some features like custom scratch buffer with specific minor-modes, copy on quit, etc, will be added over time.

* Usage

Fonctionalities are limited for now to this:
- you can create a scratch buffer with the current mode you are using =omni-scratch-major=.
  Calling it a second time from the scratch buffer will bring you back to the buffer you came from
- you can create a scratch buffer attached to your current buffer with =omni-scratch-buffer=
- you can create a new scratch buffer with =omni-scratch=.
  (Default to =fundamental-mode=, configurable with =omni-scratch-default-mode=)
- you can go to the latest edited scratch with =omni-scratch-goto-latest=
- you can quit a scratch buffer with =omni-scratch-quit= which will save its content to the kill ring
- you can select a buffer from a list if helm is installed with =omni-scratch-buffers=
- calling a scratch function with <kbd>C-U</kbd>, the universal arg, open the scratch buffer in other window

* Installation
You can install it from melpa, or put the files in your load path, and require it.

If you use [[https://github.com/jwiegley/use-package][use-package]] you could use the following config
#+begin_src emacs-lisp
  (use-package omni-scratch
      :bind (("M-s $ DEL" . omni-scratch)
             ("M-s $ -" . omni-scratch-major)
             ("M-s $ _" . omni-scratch-buffer)
             ("M-s $ $" . omni-scratch-goto-latest)
             ("M-s $ b" . omni-scratch-buffers)))
#+end_src


* About

This is still a *prototype*. So if ever you think about using it, prefer the =master= branch or elpa stable, and expect to update your config from times to times until stabilization.

Name of function and even behavior might change, so don't be suprised. This will be reported in the [[./CHANGELOG.md][Changelog]].

*If you have any remark, refactor suggestion or else, just pose an issue ;)*
